plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.6'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.bytebook'
version = '0.0.1-SNAPSHOT'
description = 'bff-tg'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'io.github.cdimascio:dotenv-java:3.2.0'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}

 tasks.register('runHttps', JavaExec) {
	 mainClass = 'com.bytebook.bfftg.BffTgApplication' // твой main класс
	 classpath = sourceSets.main.runtimeClasspath
	 jvmArgs = [
			 "-Dserver.port=${System.getenv('SERVER_PORT') ?: '8443'}",
			 "-Dserver.ssl.key-store=${System.getenv('SSL_KEY_STORE')}",
			 "-Dserver.ssl.key-store-password=${System.getenv('SSL_KEY_STORE_PASSWORD')}",
			 "-Dserver.ssl.key-store-type=PKCS12",
			 "-Dserver.ssl.key-alias=${System.getenv('SSL_KEY_ALIAS')}"
	 ]
 }
