version: '3.9'

services:
  app:
    build: .
    ports:
      - "8443:8443"
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - SSL_KEY_STORE=./keystore.p12
      - SSL_KEY_STORE_PASSWORD=${SSL_KEY_STORE_PASSWORD}
      - SSL_KEY_ALIAS=${SSL_KEY_ALIAS}
      - BOT_TOKEN=${BOT_TOKEN}

  ngrok:
    image: ngrok/ngrok:latest
    platform: linux/amd64
    depends_on:
      - app
    command: ngrok http https://app:8443
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    ports:
      - "4040:4040"
